version: '3.8'

services:
  backend:
    build: .
    command: php yii serve --port=8000
    volumes:
      - .:/app
    restart: always
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wsr25
      MYSQL_USER: wsr25
      MYSQL_PASSWORD: wsr25
      MYSQL_DATABASE: moduleG

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:8080"
    environment:
      - PMA_ARBITRARY=1
