# Generated by Django 4.2.13 on 2025-05-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('place', models.CharField(max_length=250)),
                ('services', models.CharField(max_length=250)),
                ('datetime', models.DateTimeField()),
                ('status', models.CharField(max_length=250)),
                ('link', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'оператор',
                'verbose_name_plural': 'Операторы',
            },
        ),
    ]
